cache:
  mount:
    - vendor/bundle
compose:
  database:
    image: postgres:9.4
build:
  image: ruby:2.2.3
  commands:
    - apt-get update
    - apt-get install -y nodejs
    - bundle install -j4 --path=vendor/bundle
    - bundle exec rake db:test:prepare
    - bundle exec rspec
