Metrics/BlockLength:
  Enabled: false

Naming/AccessorMethodName:
  Exclude:
    - 'spec/support/login_macros.rb'

# TODO: Add unique index later
Rails/UniqueValidationWithoutIndex:
  Exclude:
    - 'app/models/contact.rb'
    - 'app/models/phone.rb'
    - 'app/models/user.rb'

Style/ClassVars:
  Exclude:
    - 'spec/support/shared_db_connection.rb'

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Exclude:
    - 'app/controllers/*'

Style/FrozenStringLiteralComment:
  Enabled: false
