version: '3'
services:
  web:
    build: .
    command:
      - "bin/rails"
      - "s"
      - "-b"
      - "0.0.0.0"
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/everydayrails?sslmode=disable"
      RAILS_ENV: production
      ZIPKIN_SERVICE_PORT: 3000
      ZIPKIN_URL: "http://zipkin:9411"
    ports:
      - 3000:3000
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: "everydayrails"
      POSTGRES_PASSWORD: "password"
  zipkin:
    image: openzipkin/zipkin:2.4.2
    ports:
      - 9411:9411
