version: '3'
services:
  web:
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/everydayrails?sslmode=disable"
      RACK_ENV: production
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 1
      ZIPKIN_ENABLED: 1
      ZIPKIN_SERVICE_PORT: 9292
      ZIPKIN_URL: "http://zipkin:9411"
    ports:
      - 9292:9292

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - 5432:5432

  zipkin:
    image: openzipkin/zipkin:2.27.1
    ports:
      - 9411:9411
