default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: password
  sslmode: disable

development:
  <<: *default
  database: everydayrails_development

test:
  <<: *default
  database: everydayrails_test

production:
  <<: *default
  database: everydayrails_production
  username: everydayrails
  password: <%= ENV['EVERYDAYRAILS_DATABASE_PASSWORD'] %>
